// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: food_logs.sql

package strggen

import (
	"context"
	"encoding/json"
	"time"
)

const createFoodLogEntry = `-- name: CreateFoodLogEntry :one

INSERT INTO user_foodlogentry (id, user_id, name, labels, time_start, time_end)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateFoodLogEntryParams struct {
	ID        string
	UserID    string
	Name      string
	Labels    json.RawMessage
	TimeStart time.Time
	TimeEnd   time.Time
}

// Storage functions for food log entries
func (q *Queries) CreateFoodLogEntry(ctx context.Context, arg CreateFoodLogEntryParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createFoodLogEntry,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Labels,
		arg.TimeStart,
		arg.TimeEnd,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createFoodLogEntryMetric = `-- name: CreateFoodLogEntryMetric :exec
INSERT INTO user_foodlogentry_metrics (user_id, foodlogentry_id, metric_key, metric_value)
VALUES (?, ?, ?, ?)
`

type CreateFoodLogEntryMetricParams struct {
	UserID         string
	FoodlogentryID string
	MetricKey      string
	MetricValue    float64
}

func (q *Queries) CreateFoodLogEntryMetric(ctx context.Context, arg CreateFoodLogEntryMetricParams) error {
	_, err := q.db.ExecContext(ctx, createFoodLogEntryMetric,
		arg.UserID,
		arg.FoodlogentryID,
		arg.MetricKey,
		arg.MetricValue,
	)
	return err
}

const deleteFoodLogEntry = `-- name: DeleteFoodLogEntry :exec
DELETE FROM user_foodlogentry WHERE user_id = ? AND id = ?
`

type DeleteFoodLogEntryParams struct {
	UserID string
	ID     string
}

func (q *Queries) DeleteFoodLogEntry(ctx context.Context, arg DeleteFoodLogEntryParams) error {
	_, err := q.db.ExecContext(ctx, deleteFoodLogEntry, arg.UserID, arg.ID)
	return err
}

const deleteFoodLogEntryMetrics = `-- name: DeleteFoodLogEntryMetrics :exec
DELETE FROM user_foodlogentry_metrics WHERE user_id = ? AND foodlogentry_id = ?
`

type DeleteFoodLogEntryMetricsParams struct {
	UserID         string
	FoodlogentryID string
}

func (q *Queries) DeleteFoodLogEntryMetrics(ctx context.Context, arg DeleteFoodLogEntryMetricsParams) error {
	_, err := q.db.ExecContext(ctx, deleteFoodLogEntryMetrics, arg.UserID, arg.FoodlogentryID)
	return err
}

const exportFoodLogEntries = `-- name: ExportFoodLogEntries :many
SELECT  ufle.user_id, ufle.id, ufle.name, ufle.labels, ufle.time_start, ufle.time_end, json_group_array(
    json_object('key', uflem.metric_key, 'value', uflem.metric_value)
  ) AS metrics
FROM user_foodlogentry ufle
INNER JOIN user_foodlogentry_metrics uflem ON ufle.id = uflem.foodlogentry_id AND uflem.user_id = ufle.user_id
WHERE ufle.user_id = ? 
GROUP BY ufle.id
ORDER BY ufle.time_start ASC
`

type ExportFoodLogEntriesRow struct {
	UserID    string
	ID        string
	Name      string
	Labels    json.RawMessage
	TimeStart time.Time
	TimeEnd   time.Time
	Metrics   interface{}
}

func (q *Queries) ExportFoodLogEntries(ctx context.Context, userID string) ([]ExportFoodLogEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, exportFoodLogEntries, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportFoodLogEntriesRow
	for rows.Next() {
		var i ExportFoodLogEntriesRow
		if err := rows.Scan(
			&i.UserID,
			&i.ID,
			&i.Name,
			&i.Labels,
			&i.TimeStart,
			&i.TimeEnd,
			&i.Metrics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFoodLogEntry = `-- name: GetFoodLogEntry :one
SELECT user_id, id, name, labels, time_start, time_end FROM user_foodlogentry WHERE user_id = ? AND id = ?
`

type GetFoodLogEntryParams struct {
	UserID string
	ID     string
}

func (q *Queries) GetFoodLogEntry(ctx context.Context, arg GetFoodLogEntryParams) (UserFoodlogentry, error) {
	row := q.db.QueryRowContext(ctx, getFoodLogEntry, arg.UserID, arg.ID)
	var i UserFoodlogentry
	err := row.Scan(
		&i.UserID,
		&i.ID,
		&i.Name,
		&i.Labels,
		&i.TimeStart,
		&i.TimeEnd,
	)
	return i, err
}

const getFoodLogEntryMetrics = `-- name: GetFoodLogEntryMetrics :many
SELECT metric_key, metric_value FROM user_foodlogentry_metrics WHERE user_id = ? AND foodlogentry_id = ?
`

type GetFoodLogEntryMetricsParams struct {
	UserID         string
	FoodlogentryID string
}

type GetFoodLogEntryMetricsRow struct {
	MetricKey   string
	MetricValue float64
}

func (q *Queries) GetFoodLogEntryMetrics(ctx context.Context, arg GetFoodLogEntryMetricsParams) ([]GetFoodLogEntryMetricsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFoodLogEntryMetrics, arg.UserID, arg.FoodlogentryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFoodLogEntryMetricsRow
	for rows.Next() {
		var i GetFoodLogEntryMetricsRow
		if err := rows.Scan(&i.MetricKey, &i.MetricValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeFoodLogEntries = `-- name: PurgeFoodLogEntries :exec
DELETE FROM user_foodlogentry WHERE user_id = ?
`

func (q *Queries) PurgeFoodLogEntries(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, purgeFoodLogEntries, userID)
	return err
}

const queryFoodLogEntries = `-- name: QueryFoodLogEntries :many
SELECT ufle.user_id, ufle.id, ufle.name, ufle.labels, ufle.time_start, ufle.time_end, json_group_array(
    json_object('key', uflem.metric_key, 'value', uflem.metric_value)
  ) AS metrics
FROM user_foodlogentry ufle
INNER JOIN user_foodlogentry_metrics uflem ON ufle.id = uflem.foodlogentry_id AND uflem.user_id = ufle.user_id
WHERE ufle.user_id = ? AND ufle.time_start >= ? AND ufle.time_end <= ?
GROUP BY ufle.id
ORDER BY ufle.time_start ASC
`

type QueryFoodLogEntriesParams struct {
	UserID    string
	TimeStart time.Time
	TimeEnd   time.Time
}

type QueryFoodLogEntriesRow struct {
	UserID    string
	ID        string
	Name      string
	Labels    json.RawMessage
	TimeStart time.Time
	TimeEnd   time.Time
	Metrics   interface{}
}

func (q *Queries) QueryFoodLogEntries(ctx context.Context, arg QueryFoodLogEntriesParams) ([]QueryFoodLogEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, queryFoodLogEntries, arg.UserID, arg.TimeStart, arg.TimeEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryFoodLogEntriesRow
	for rows.Next() {
		var i QueryFoodLogEntriesRow
		if err := rows.Scan(
			&i.UserID,
			&i.ID,
			&i.Name,
			&i.Labels,
			&i.TimeStart,
			&i.TimeEnd,
			&i.Metrics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFoodLogEntry = `-- name: UpdateFoodLogEntry :exec
UPDATE user_foodlogentry
SET name = ?, labels = ?, time_start = ?, time_end = ?
WHERE user_id = ? AND id = ?
`

type UpdateFoodLogEntryParams struct {
	Name      string
	Labels    json.RawMessage
	TimeStart time.Time
	TimeEnd   time.Time
	UserID    string
	ID        string
}

func (q *Queries) UpdateFoodLogEntry(ctx context.Context, arg UpdateFoodLogEntryParams) error {
	_, err := q.db.ExecContext(ctx, updateFoodLogEntry,
		arg.Name,
		arg.Labels,
		arg.TimeStart,
		arg.TimeEnd,
		arg.UserID,
		arg.ID,
	)
	return err
}
