// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package strggen

import (
	"encoding/json"
	"time"
)

type Test struct {
	Something *string
}

type UserConfig struct {
	UserID      string
	ID          string
	ConfigValue json.RawMessage
}

type UserFoodlogentry struct {
	UserID    string
	ID        string
	Name      string
	Labels    json.RawMessage
	TimeStart time.Time
	TimeEnd   time.Time
}

type UserFoodlogentryMetric struct {
	UserID         string
	FoodlogentryID string
	MetricKey      string
	MetricValue    float64
}
