// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package strggen

import (
	"context"
)

type Querier interface {
	// Storage functions for food log entries
	CreateFoodLogEntry(ctx context.Context, arg CreateFoodLogEntryParams) (string, error)
	CreateFoodLogEntryMetric(ctx context.Context, arg CreateFoodLogEntryMetricParams) error
	DeleteFoodLogEntry(ctx context.Context, arg DeleteFoodLogEntryParams) error
	DeleteFoodLogEntryMetrics(ctx context.Context, arg DeleteFoodLogEntryMetricsParams) error
	ExportFoodLogEntries(ctx context.Context, userID string) ([]ExportFoodLogEntriesRow, error)
	GetFoodLogEntry(ctx context.Context, arg GetFoodLogEntryParams) (UserFoodlogentry, error)
	GetFoodLogEntryMetrics(ctx context.Context, arg GetFoodLogEntryMetricsParams) ([]GetFoodLogEntryMetricsRow, error)
	GetTestData(ctx context.Context) (*string, error)
	// Storage functions for user config
	GetUserConfig(ctx context.Context, arg GetUserConfigParams) (UserConfig, error)
	PurgeFoodLogEntries(ctx context.Context, userID string) error
	QueryFoodLogEntries(ctx context.Context, arg QueryFoodLogEntriesParams) ([]QueryFoodLogEntriesRow, error)
	StoreUserConfig(ctx context.Context, arg StoreUserConfigParams) error
	UpdateFoodLogEntry(ctx context.Context, arg UpdateFoodLogEntryParams) (string, error)
}

var _ Querier = (*Queries)(nil)
