services:
  postgres:
    image: postgres:18
    restart: always
    env_file:
      - .env-compose
    ports:
      - 5435:5432

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3022:8080
    env_file:
      - .env-compose
    depends_on:
      - postgres
    develop:
      watch:
        - action: rebuild
          path: .

