apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openfooddiary
  namespace: {{ .Release.Namespace }}
  name: openfooddiary
spec:
  replicas: {{ required "replicas is required" .Values.replicas }}
  selector:
    matchLabels:
      app: openfooddiary
  template:
    metadata:
      labels:
        app: openfooddiary
      namespace: {{ .Release.Namespace }}
      name: openfooddiary
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '3024'
    spec:
      containers:
        - name: openfooddiary
          image: {{ required "image is required" .Values.image }}:{{  required "tag is required" .Values.tag }}
          ports:
            - name: web
              containerPort: 3024
          env:
            - name: OPENFOODDIARY_USERIDHEADER
              value: x-auth-request-user
            - name: OPENFOODDIARY_PORT
              value: "3024"
            - name: PORT
              value: "3024"
            - name: OPENFOODDIARY_STORAGE_PROVIDER
              value: postgres
            - name: OPENFOODDIARY_LOGOUT_ENDPOINT
              value: {{ .Values.signoutUrl }}
            - name: OPENFOODDIARY_POSTGRES_CONNECTION_STRING
              value: {{ .Values.postgres.url }}
