apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openfooddiary
  namespace: {{ .Release.Namespace }}
  name: openfooddiary
spec:
  replicas: {{ required "replicas is required" .Values.replicas }}
  selector:
    matchLabels:
      app: openfooddiary
  template:
    metadata:
      labels:
        app: openfooddiary
      namespace: {{ .Release.Namespace }}
      name: openfooddiary
    spec:
      containers:
        - name: openfooddiary
          image: {{ required "image is required" .Values.image }}:{{  required "tag is required" .Values.tag }}
          ports:
            - name: web
              containerPort: 3024
          env:
            - name: OPENFOODDIARY_PORT
              value: "3024"
            - name: PORT
              value: "3024"
            - name: OPENFOODDIARY_STORAGE_PROVIDER
              value: postgres
            - name: OPENFOODDIARY_POSTGRES_CONNECTION_STRING
              value: {{ .Values.postgres.url }}
            {{- if .Values.userId }}
            - name: OPENFOODDIARY_USERID
              value: {{ .Values.userId | quote }}
            {{- else }}
            - name: OPENFOODDIARY_OAUTH2_ISSUER
              value: {{ required "oauth2.issuer is required unless userId is set" .Values.oauth2.issuer | quote }}
            - name: OPENFOODDIARY_OAUTH2_CLIENT_ID
              value: {{ required "oauth2.clientId is required unless userId is set" .Values.oauth2.clientId | quote }}
            - name: OPENFOODDIARY_OAUTH2_CLIENT_SECRET
              value: {{ .Values.oauth2.clientSecret | quote }}
            - name: OPENFOODDIARY_OAUTH2_REDIRECT_URL
              value: {{ .Values.oauth2.redirectUrl | quote }}
            - name: OPENFOODDIARY_SESSION_REDIS_URL
              value: {{ required "redis.url is required unless userId is set" .Values.redis.url | quote }}
            - name: OPENFOODDIARY_SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sessionSecretName }}
                  key: session-secret
            {{- end }}
