// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: food_logs.sql

package strggen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFoodLogEntry = `-- name: CreateFoodLogEntry :one

INSERT INTO user_foodlogentry (user_id, id, name, labels, time_start, time_end)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING user_id, id, name, labels, time_start, time_end
`

type CreateFoodLogEntryParams struct {
	UserID    string
	ID        uuid.UUID
	Name      string
	Labels    []string
	TimeStart pgtype.Timestamp
	TimeEnd   pgtype.Timestamp
}

// Storage functions for food log entries
func (q *Queries) CreateFoodLogEntry(ctx context.Context, arg CreateFoodLogEntryParams) (UserFoodlogentry, error) {
	row := q.db.QueryRow(ctx, createFoodLogEntry,
		arg.UserID,
		arg.ID,
		arg.Name,
		arg.Labels,
		arg.TimeStart,
		arg.TimeEnd,
	)
	var i UserFoodlogentry
	err := row.Scan(
		&i.UserID,
		&i.ID,
		&i.Name,
		&i.Labels,
		&i.TimeStart,
		&i.TimeEnd,
	)
	return i, err
}

const createFoodLogEntryMetric = `-- name: CreateFoodLogEntryMetric :exec
INSERT INTO user_foodlogentry_metrics (user_id, foodlogentry_id, metric_key, metric_value)
VALUES ($1, $2, $3, $4)
`

type CreateFoodLogEntryMetricParams struct {
	UserID         string
	FoodlogentryID uuid.UUID
	MetricKey      string
	MetricValue    int32
}

func (q *Queries) CreateFoodLogEntryMetric(ctx context.Context, arg CreateFoodLogEntryMetricParams) error {
	_, err := q.db.Exec(ctx, createFoodLogEntryMetric,
		arg.UserID,
		arg.FoodlogentryID,
		arg.MetricKey,
		arg.MetricValue,
	)
	return err
}

const deleteFoodLogEntry = `-- name: DeleteFoodLogEntry :exec
DELETE FROM user_foodlogentry WHERE user_id = $1 AND id = $2
`

type DeleteFoodLogEntryParams struct {
	UserID string
	ID     uuid.UUID
}

func (q *Queries) DeleteFoodLogEntry(ctx context.Context, arg DeleteFoodLogEntryParams) error {
	_, err := q.db.Exec(ctx, deleteFoodLogEntry, arg.UserID, arg.ID)
	return err
}

const deleteFoodLogEntryMetrics = `-- name: DeleteFoodLogEntryMetrics :exec
DELETE FROM user_foodlogentry_metrics WHERE user_id = $1 AND foodlogentry_id = $2
`

type DeleteFoodLogEntryMetricsParams struct {
	UserID         string
	FoodlogentryID uuid.UUID
}

func (q *Queries) DeleteFoodLogEntryMetrics(ctx context.Context, arg DeleteFoodLogEntryMetricsParams) error {
	_, err := q.db.Exec(ctx, deleteFoodLogEntryMetrics, arg.UserID, arg.FoodlogentryID)
	return err
}

const exportFoodLogEntries = `-- name: ExportFoodLogEntries :many
SELECT user_id, id, name, labels, time_start, time_end FROM user_foodlogentry WHERE user_id = $1 ORDER BY time_start ASC
`

func (q *Queries) ExportFoodLogEntries(ctx context.Context, userID string) ([]UserFoodlogentry, error) {
	rows, err := q.db.Query(ctx, exportFoodLogEntries, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserFoodlogentry
	for rows.Next() {
		var i UserFoodlogentry
		if err := rows.Scan(
			&i.UserID,
			&i.ID,
			&i.Name,
			&i.Labels,
			&i.TimeStart,
			&i.TimeEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportFoodLogEntryMetrics = `-- name: ExportFoodLogEntryMetrics :many
SELECT foodlogentry_id, metric_key, metric_value FROM user_foodlogentry_metrics WHERE user_id = $1
`

type ExportFoodLogEntryMetricsRow struct {
	FoodlogentryID uuid.UUID
	MetricKey      string
	MetricValue    int32
}

func (q *Queries) ExportFoodLogEntryMetrics(ctx context.Context, userID string) ([]ExportFoodLogEntryMetricsRow, error) {
	rows, err := q.db.Query(ctx, exportFoodLogEntryMetrics, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportFoodLogEntryMetricsRow
	for rows.Next() {
		var i ExportFoodLogEntryMetricsRow
		if err := rows.Scan(&i.FoodlogentryID, &i.MetricKey, &i.MetricValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFoodLogEntry = `-- name: GetFoodLogEntry :one
SELECT user_id, id, name, labels, time_start, time_end FROM user_foodlogentry WHERE user_id = $1 AND id = $2
`

type GetFoodLogEntryParams struct {
	UserID string
	ID     uuid.UUID
}

func (q *Queries) GetFoodLogEntry(ctx context.Context, arg GetFoodLogEntryParams) (UserFoodlogentry, error) {
	row := q.db.QueryRow(ctx, getFoodLogEntry, arg.UserID, arg.ID)
	var i UserFoodlogentry
	err := row.Scan(
		&i.UserID,
		&i.ID,
		&i.Name,
		&i.Labels,
		&i.TimeStart,
		&i.TimeEnd,
	)
	return i, err
}

const getFoodLogEntryMetrics = `-- name: GetFoodLogEntryMetrics :many
SELECT metric_key, metric_value FROM user_foodlogentry_metrics WHERE user_id = $1 AND foodlogentry_id = $2
`

type GetFoodLogEntryMetricsParams struct {
	UserID         string
	FoodlogentryID uuid.UUID
}

type GetFoodLogEntryMetricsRow struct {
	MetricKey   string
	MetricValue int32
}

func (q *Queries) GetFoodLogEntryMetrics(ctx context.Context, arg GetFoodLogEntryMetricsParams) ([]GetFoodLogEntryMetricsRow, error) {
	rows, err := q.db.Query(ctx, getFoodLogEntryMetrics, arg.UserID, arg.FoodlogentryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFoodLogEntryMetricsRow
	for rows.Next() {
		var i GetFoodLogEntryMetricsRow
		if err := rows.Scan(&i.MetricKey, &i.MetricValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeFoodLogEntries = `-- name: PurgeFoodLogEntries :exec
DELETE FROM user_foodlogentry WHERE user_id = $1
`

func (q *Queries) PurgeFoodLogEntries(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, purgeFoodLogEntries, userID)
	return err
}

const queryFoodLogEntries = `-- name: QueryFoodLogEntries :many
SELECT user_id, id, name, labels, time_start, time_end FROM user_foodlogentry
WHERE user_id = $1 AND time_start >= $2 AND time_end <= $3
ORDER BY time_start ASC
`

type QueryFoodLogEntriesParams struct {
	UserID    string
	TimeStart pgtype.Timestamp
	TimeEnd   pgtype.Timestamp
}

func (q *Queries) QueryFoodLogEntries(ctx context.Context, arg QueryFoodLogEntriesParams) ([]UserFoodlogentry, error) {
	rows, err := q.db.Query(ctx, queryFoodLogEntries, arg.UserID, arg.TimeStart, arg.TimeEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserFoodlogentry
	for rows.Next() {
		var i UserFoodlogentry
		if err := rows.Scan(
			&i.UserID,
			&i.ID,
			&i.Name,
			&i.Labels,
			&i.TimeStart,
			&i.TimeEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryFoodLogEntryMetrics = `-- name: QueryFoodLogEntryMetrics :many
SELECT foodlogentry_id, metric_key, metric_value FROM user_foodlogentry_metrics
WHERE user_id = $1 AND foodlogentry_id = ANY($2::uuid[])
`

type QueryFoodLogEntryMetricsParams struct {
	UserID  string
	Column2 []uuid.UUID
}

type QueryFoodLogEntryMetricsRow struct {
	FoodlogentryID uuid.UUID
	MetricKey      string
	MetricValue    int32
}

func (q *Queries) QueryFoodLogEntryMetrics(ctx context.Context, arg QueryFoodLogEntryMetricsParams) ([]QueryFoodLogEntryMetricsRow, error) {
	rows, err := q.db.Query(ctx, queryFoodLogEntryMetrics, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryFoodLogEntryMetricsRow
	for rows.Next() {
		var i QueryFoodLogEntryMetricsRow
		if err := rows.Scan(&i.FoodlogentryID, &i.MetricKey, &i.MetricValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFoodLogEntry = `-- name: UpdateFoodLogEntry :one
UPDATE user_foodlogentry
SET name = $3, labels = $4, time_start = $5, time_end = $6
WHERE user_id = $1 AND id = $2
RETURNING user_id, id, name, labels, time_start, time_end
`

type UpdateFoodLogEntryParams struct {
	UserID    string
	ID        uuid.UUID
	Name      string
	Labels    []string
	TimeStart pgtype.Timestamp
	TimeEnd   pgtype.Timestamp
}

func (q *Queries) UpdateFoodLogEntry(ctx context.Context, arg UpdateFoodLogEntryParams) (UserFoodlogentry, error) {
	row := q.db.QueryRow(ctx, updateFoodLogEntry,
		arg.UserID,
		arg.ID,
		arg.Name,
		arg.Labels,
		arg.TimeStart,
		arg.TimeEnd,
	)
	var i UserFoodlogentry
	err := row.Scan(
		&i.UserID,
		&i.ID,
		&i.Name,
		&i.Labels,
		&i.TimeStart,
		&i.TimeEnd,
	)
	return i, err
}
