// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package strggen

import (
	"context"
)

type Querier interface {
	GetTestData(ctx context.Context) (*string, error)
}

var _ Querier = (*Queries)(nil)
