// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: test.sql

package strggen

import (
	"context"
)

const getTestData = `-- name: GetTestData :one
SELECT something FROM test LIMIT 1
`

func (q *Queries) GetTestData(ctx context.Context) (*string, error) {
	row := q.db.QueryRow(ctx, getTestData)
	var something *string
	err := row.Scan(&something)
	return something, err
}
