// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_config.sql

package strggen

import (
	"context"
)

const getUserConfig = `-- name: GetUserConfig :one

SELECT user_id, id, config_value FROM user_config WHERE user_id = $1 AND id = $2
`

type GetUserConfigParams struct {
	UserID string
	ID     string
}

// Storage functions for user config
func (q *Queries) GetUserConfig(ctx context.Context, arg GetUserConfigParams) (UserConfig, error) {
	row := q.db.QueryRow(ctx, getUserConfig, arg.UserID, arg.ID)
	var i UserConfig
	err := row.Scan(&i.UserID, &i.ID, &i.ConfigValue)
	return i, err
}

const storeUserConfig = `-- name: StoreUserConfig :exec
INSERT INTO user_config (user_id, id, config_value)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, id) DO UPDATE SET config_value = EXCLUDED.config_value
`

type StoreUserConfigParams struct {
	UserID      string
	ID          string
	ConfigValue []byte
}

func (q *Queries) StoreUserConfig(ctx context.Context, arg StoreUserConfigParams) error {
	_, err := q.db.Exec(ctx, storeUserConfig, arg.UserID, arg.ID, arg.ConfigValue)
	return err
}
