apiVersion: v1
kind: Service
metadata:
  labels:
    app: openfooddiary
  name: openfooddiary
spec:
  ports:
    - name: http
      port: 3012
      protocol: TCP
      targetPort: web
  selector:
    app: openfooddiary
  type: ClusterIP