name: Container Build and Test

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *" # run at 2 AM UTC
  push:
    branches: ["main"]
  pull_request:

jobs:
  publish-bleed:
    uses: ./.github/workflows/build_docker_image.yml
    with:
      VERSION: test
      PUSH: false
      PUSH_LATEST: false