name: Build and Publish OpenFoodDiary Container

on:
  workflow_call:
    inputs:
      VERSION:
        type: string
        required: true
      PUSH:
        type: boolean
        default: false
        required: false
      PUSH_LATEST:
        type: boolean
        default: false
        required: false

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      RUN_TAG: ghcr.io/openhealthsuite/diary:${{ github.run_id }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: "1.25"
          cache: true
          cache-dependency-path: 'go.sum'
      - name: Install playwright
        run: go run github.com/playwright-community/playwright-go/cmd/playwright@v0.5700.1 install --with-deps

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Version
        uses: docker/build-push-action@v7
        with:
          context: .
          push: false
          load: true
          tags: ghcr.io/openhealthsuite/diary:${{github.run_id}}
      
      - name: Test Image
        run: |
          docker run --name=ofgtest -d -e PORT=3011 -p 3011:3011 ghcr.io/openhealthsuite/diary:${{github.run_id}}
          MAX_WAIT=10
          INTERVAL=1
          i=0
          until curl --output /dev/null --silent --fail http://localhost:3011/api/ping; do
            i=$((i+INTERVAL))
            if [ "$i" -ge "$MAX_WAIT" ]; then
              echo "Timed out waiting for API after ${MAX_WAIT}s"
              exit 1
            fi
            sleep ${INTERVAL}
          done
          OFD_E2E_TARGET='http://localhost:3011' go test ./tests/e2e/...

      - name: Push Version
        if: ${{ inputs.PUSH }}
        uses: docker/build-push-action@v7
        with:
          context: .
          platforms: linux/arm64/v8,linux/amd64
          push: true
          tags: ghcr.io/openhealthsuite/diary:${{ inputs.VERSION }}

      - name: Push Latest
        if: ${{ inputs.PUSH && inputs.PUSH_LATEST }}
        uses: docker/build-push-action@v7
        with:
          context: .
          platforms: linux/arm64/v8,linux/amd64
          push: true
          tags: ghcr.io/openhealthsuite/diary:latest
